# default data location is next to /Kaggle-Chest-X-ray-Abnormalities-Detection:
#    /parent_folder
#       /Kaggle-Chest-X-ray-Abnormalities-Detection
#       /train_dataset


train: ../train_dataset/images
val: ../train_dataset/images

# number of classes
nc: 14

# class names
names: ['Aortic enlargement', 'Atelectasis', 'Calcification', 'Cardiomegaly', 'Consolidation', 'ILD', 'Infiltration',
        'Lung Opacity', 'Nodule/Mass', 'Other lesion', 'Pleural effusion', 'Pleural thickening', 'Pneumothorax',
        'Pulmonary fibrosis']